export const prompts = [
"How did you celebrate New Year's Day?",
"What do you want to improve on this year?",
"Write down your last sent text message.",
"What is your greatest memory?", 
"Who do you miss?",
"What scares you?", 
"Do you have a plan? Do you need a plan?",
"Nobody knows that I . . .",
"Do you believe in fate?",
"Are you easy to get along with?",
"The most terrifying moment of my life was . . .",
"Three things you can’t go without.",
"5 People.",
"Write down a secret.",
"What makes you proud?",
"What is something weird that you like?",
"What stresses you out?",
"What are you good at?",
"Fine, whatever . . .", 
"3 innovations.",
"Did you complete your to-do list for today?",
"what is the best part about your life right now?",
"What would you like to tell your parents?",
"Who do you live with?",
"List what you have in your bag/backpack",
"When is the last time you danced?",
"What is the oldest thing you are wearing today?",
"The most surprised I’ve ever been . . .",
"What is your resolution for tomorrow?",
"Wben was the last time you worked out?",
"5 things to do less often.",
"What are you chasing at this moment?",
"The last thing you celebrated.",
"What do you want to be remembered for?",
"When was the last time you failed?",
"Who can help you?",
"What are you confident about?",
"Your most recent regret.",
"What is your next major deadline?",
"What is your favorite cuisine?",
"What was the last promise you made? Did you keep it?",
"Look outside, what do you see?",
"What frustrates you about a friend or a partner?",
"What is the best compliment that someone can receive?",
"Did you kiss anyone recently?", // Valentines day
"What bullet have you recently dodged?",
"What do you have too much of?",
"What do you spend most of your time doing?",
"List 3 things on your bucket list.",
"Do you like being alone?",
"Write down the weirdest sentence you can make up.",
"What are your top 3 priorities in life?",
"How many pairs of shoes do you have?",
"Bad news: sugarcoated or straight up?",
"The most disappointed I’ve ever been . . .",
"Describe an embarassing moment.",
"What are you looking forward to the most?",
"What are your hobbies?",
"Who do you trust the most?", 
"The first thing I ate today was . . .", // leap day
"Would you get plastic surgery? On what part of your body?",
"List 5 things that were on your to do list today.",
"Dear ____, it weighs on me that I never told you . . .",
"How hungry are you right now?",
"If you had to choose one food for the rest of your life, what would it be?",
"What are you a geek about?",
"Who was kind to you today?",
"What matters today?",
"Where do you wish you were right now?",
"3 Smells.",
"What did you once hate but now like?",
"Describe a crush.", 
"What was the last movie you watched?",
"I want a new ____",
"The biggest lie I’ve ever told is . . .",
"Have you been pinched recently?", // St patricks
"If you won a lottery, what would you do?",
"One word for today.",
"You have no patience for ____",
"What expressions do you overuse?",
"Spell your full name with your nose.",
"You wake up at ___",
"There is no such thing as too much _____", 
"Is there anything you feel guilty about?",
"What's the most valuable thing you own?",
"What are your priorities for the week?",
"What was your last credit card purchase?",
"Describe a sound you heard today.",
"What is a current news headline people are talking about?",
"What is the last person in your missed calls?",
"Write a haiku about your day.",
"I feel amazing when. . .", 
"Today you made ____",
"What time did you go to bad last night?",
"A favorite song lyric.",
"What are you obsessed with right now?",
"If you only could choose one memory to retain, which memory would it be?",
"Who is someone who made you proud?",
"Describe a typical outfit you would wear.",
"What was the last risk you took?",
"What would you like to have written on your gravestone?",
"What details from today would you like to remember?",
"Do you want to know how it ends?",
"What was the last present you gave to someone?",
"What do you see in the mirror today?",
"What’s the worst thing you’ve ever done?",
"Do you feel appreciated?",
"On a scale of 1 - 10 how happy are you?",
"Who do you miss?",
"How ambitious do you feel today?",
"What do you need to do more often?",
"Write a letter to your boss",
"Write down the text message you most recently read.",
"Where do you see yourself next year?",
"What is something new in your life?",
"Would you rather lose all your valuables or all the pictures you've ever taken?",
"What surprised you today?",
"how was your day?",
"Write about the first thing that comes to your mind right now.",
"What was the last dream you remember?",
"What is the best advice anyone has ever told you?",
"What are the last three things you used today?",
"What is your most recent act of generosity?",
"Where do you find joy?",
"What do you like to talk about?",
"Are you a role model to anyone?",
"Today, I had too much ____",
"What are 2 things that bring you joy that you can't buy with money?",
"If you had to move to a new city, where would you move to?",
"What are three words to describe your social life?",
"3 random facts about you.",
"If you could change one thing about today, what would it be?",
"What is something you learned from your mother?", // Mother's Day
"Did you meet someone new recently? If so, who?",
"What was the last song you listened to?",
"If you could be the best at anything, what would it be?",
"What is your favorite cereal?",
"Does anything hurt today?",
"Who is someone who made you sad?",
"Name 3 things on your plan-to-watch list?",
"What’s your secret desire?",
"What have you been up to lately?",
"Who was the last person you spoke with in person?",
"Discuss a quirk of yours",
"The most fun I’ve ever had . . .",
"Write down five words that describe today.",
"____ is perfect.",
"What do you think is cute?",
"Your favorite color.",
"Write down a problem you solved today.",
"What are your priorities for the month?",
"Who makes you the happiest?",
"The last person you held hands with.",
"Where do you live? Who do you live with?",
"What do you think is your biggest shortcoming?",
"How could today have been better?",
"When was the last time you were sick?",
"Write down a new fact your recently learned.",
"Three favorite things to wear.",
"Describe your favorite pair of shoes",
"Your most recent grocery list.",
"What is your take on soul mates?",
"How old do you want to live to?",
"What is the most recent conversation you overheard?",
"From time to time. . .",
"Favorite beverage.",
"When was the last time you spoke to your parents?",
"When was the last time you told your dad that you loved him?", // Fathers day
"Where do you feel most at home?",
"How do you keep organized?",
"Recently, what hardships are you facing?",
"Would you rather be forgotten by everyone, or lose all your memories?",
"How comfortable are you with lying?",
"5 things to do more often.",
"What is your least favorite beverage?",
"Three favorite TV shows.",
"What was the last time you thanked someone?",
"Pick a color.",
"What is your motto?",
"If you could relive an experience in your life, what would it be?",
"Are you in love?",
"The last birthday you celebrated was . . .",
"What is the next big step you need to take?",
"Describe yourself today.",
"____ made you laugh today",
"Have you every done anything illegal?",
"What did you daydream about today?",
"How do you show love?",
"How do you cope with worry?", 
"What do you crave?",
"Who or what means the world to you?",
"What have you been cooking recently?",
"3 ways to win your heart.",
"What is a promise you made to yourself?",
"What was the last spontaneous thing you did?",
"List 3 things that make you smile.",
"Dear Past Me . . .", 
"What was the last movie you saw in the theaters?",
"Who do you want to know better?",
"What is the last meal someone cooked for you?",
"What makes you cynical?",
"What do you want to postpone?",
"What is the most recent event you went to?",
"The hardest time of my days are. . .",
"What do you wish you had said?",
"Who do you want to see the most right now?",
"Who is someone who made you happy?",
"How do you want to be remembered?",
"What is your dream vacation?",
"Are you saving or spending?",
"What is the last photo you took on your phone?",
"When was the last time you went swimming?",
"If you could have a superpower just for today, what would it be?",
"Is your room messy or clean right now?",
"Who makes you the happiest?",
"What was the last party you went to?",
"10 Web Sites",
"What is your current favorite snacks?",
"What do you want to forget?",
"3 Business ideas",
"Are you lucky?",
"Describe your current romantic relationship.",
"What was the last present you received?",
"On a scale of 1 - 10, how attractive do you think you are?",
"Today was tough because ____",
"Write about a teacher you had.",
"Today I wore...",
"What did you have for lunch today?",
"Which family member are you the closest to?",
"What do you feel grateful for today?",
"What if . . .",
"What is your least favorite word?",
"What advice would you give to a second grader?",
"The last time you were drunk.",
"If you didn't have responsibilities today, what would you be doing?",
"What makes you miserable?",
"Who is your role model?",
"What relaxes you?",
"What was the last thing you splurged money on?",
"What's the craziest thing you've done for love?",
"What's your salary?",
"Describe a childhood memory.",
"And then all of a sudden. . .",
"Who was the last person to make you angry?",
"What was the last road trip you took?",
"What did you do during summer?",
"Describe the room you are in right now.",
"What do you spend most of your money on?",
"On a scale of 1 - 10, how healthy are you?",
"What's your hairstyle?",
"What would you do right now if you were not afraid?",
"What do you wish you had left unsaid?",
"List your pets.",
"What bothered you today?",
"Top 3 wishes.",
"What did you give up on?",
"Do you ever have a feeling of deja-vu? Try your best to recall it.",
"On a scale of 1 - 10 how sad are you?",
"What is your mission?",
"How much do you curse?",
"Who is the first person you saw today?",
"What do you want to learn?",
"What was the last thing that hurt you?",
"Timeline your day with bullet points.",
"What is the first thing you saw when you woke up this morning?",
"What is your mood today?",
"Who is the last person to tell you they loved you?",
"Is something in your way?",
"Do you think anyone doesn't like you?",
"3 Goals for the next week.",
"What are you struggling with?",
"Your last deep conversation.",
"What's your simplest pleasure?",
"List the past 5 people you messaged on social media.",
"Spell your full name with your chin.",
"what is the newest thing you are wearing today?",
"What are you jealous of?",
"When is the last time you stopped to appreciate nature?",
"How many hours did you spend on technology today?",
"What is the last online video clip you watched?",
"Write a letter of advice to yourself last year",
"5 words that describe you.",
"What have you been doing for fun recently?",
"Who are the most important people in your life?",
"What's a new place you've recently been to?",
"What is your biggest regret?",
"Are you holding a grudge?",
"Three pet peeves.",
"It's so clear to me now. . .",
"Would you kiss the last person you kissed again?",
"If you could be any nationality what would it be?",
"The most recent compliment you received.",
"What was your last great meal?",
"I miss . . .",
"Who is the strongest person you know?",
"3 Life Lessons.",
"Who are you?",
"What was the last hilarious post you saw on a social media website?",
"What do you lie about?",
"What are your costume ideas for this halloween?", // Halloween
"The funniest thing you heard today.",
"Any plans for halloween?", // Halloween
"List the last 5 people who messaged you on social media.",
"Try to describe what you ate for dinner in no less than 10 sentences.",
"Are you working hard or hardly working?",
"What can you smell right now?",
"What makes you mad?",
"How much time did you have for yourself today?",
"What do you need to throw away?",
"In the case of a natural disaster, what three things would you take with you?",
"Who is your best friend?",
"What do you have to lose?",
"Today was delightful because ____",
"3 foods I dislike.",
"What are your bad habits?",
"Dear Future Me . . .",
"What was the last beach you went to?",
"Make a list of 5 rules you live by.",
"What color is your toothbrush?",
"What can you live without right now?",
"What was the last time you got in trouble?",
"What have you been listening to recently?",
"Do you owe anyone money?",
"What is your greatest strength?",
"What do you hope people say about you?",
"If your mood were a weather forecast, you would be a _____",
"What is something you are waiting to go on sale?", // Black Friday
"What is your next social engagement?",
"When was the last time you cried?",
"Today I chose to _____",
"What is your favorite place?",
"What was the last thing you apologized for?",
"What are you excited for this upcoming week?",
"4 Desserts.",
"What keeps you up at night?",
"Do you love your job?",
"Did you smile or frown more today?",
"Who is the last person you saw today?",
"What is your favorite word?",
"If you had to spend 5 years in prison, what would you finally have the chance to do?",
"What do you like best about your body today?",
"Where would you go if you were invisible?",
"Do you make enough money?",
"When was the last time you felt scared?",
"I live for. . .",
"How critical are you of yourself?",
"If today was your last day, how would you spend it?",
"What are you self-conscious about?",
"What do you like about yourself?",
"If you could run any business (gauranteed to succeed), what would it be?",
"What decision are you glad that you made?",
"The last person you became intimate with.",
"What do you wish your parents did differently while raising you?",
"First 10 words to come up to your mind.",
"Did you make someone laugh today? Was it intentional?",
"Your favorite piece of clothing.",
"What store do you shop at the most?",
"How do you plan to celebrate Christmas?", // Christmas
"Your top 10 Songs of the Year.",
"If you could redo this year, what is one thing you would do differently?",
"What presents did you receive for Christmas this year?",
"What achievement from the past year are you most proud about?",
"How are you different from your one-year-ago self?",
"Your most cherished memory of this year.",
"Write a timeline of your year to the best of your ability.",
"Summarize your year in at most 5 words.",
];

// this year includes a leap day
var startDate = new Date(2016, 0, 1);
var endDate = new Date(2016, 11, 31);
const monthNames = ["January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];
var getDateArray = function(start, end) {
    var arr = new Array();
    var dt = new Date(start);
    while (dt <= end) {
        arr.push(monthNames[dt.getMonth()]+" "+dt.getDate());
        dt.setDate(dt.getDate() + 1);
    }
    return arr;
}

export const dates = getDateArray(startDate, endDate);